# Default configuration for extension with alias: "swoole"
swoole:
  http_server:
    host: 0.0.0.0
    port: 1215
    hmr: "inotify"
    static:
      strategy: off # One of "off"; "default"; "advanced"; "auto"
      public_dir: '%kernel.project_dir%/public'
    exception_handler:
      type: auto # One of "json"; "production"; "custom"; "auto"
      verbosity: auto # One of "trace"; "verbose"; "default"; "auto"
    settings:
      log_file: '%kernel.logs_dir%/swoole_%kernel.environment%.log'
      log_level: auto # One of "auto"; "debug"; "trace"; "info"; "notice"; "warning"; "error"
      #       pid_file: '%kernel.logs_dir%/swoole.pid'
      worker_count: 1
      reactor_count: 1


# php bin/console config:dump-reference debug
# php bin/console debug:config debug
# bin/console swoole:server:run