trikoder_oauth2:

    authorization_server:
        private_key: '%kernel.project_dir%/var/keys/private.key'                 # Change this
        private_key_passphrase: null                            # Passphrase of the private key, if any

        encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'   # (Optional) Change this

        enable_password_grant: true

    resource_server:
        public_key: '%kernel.project_dir%/var/keys/public.key'                       # Change this

    persistence:
        doctrine: null
    scopes:
        - read
