version: '3.4'

services:

  nginx:
    container_name: 'nginx'
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './.docker/nginx/conf.d:/etc/nginx/conf.d'
      - './.docker/nginx/logs:/var/log/nginx'
      - './:/var/www/html'
    depends_on:
      - php-swoole

  php-swoole:
    container_name: 'php-swoole'
    image: 'aleksajo/swoole-server'
    command: 'bash -c "tail -f /dev/null"'
    volumes:
      - './:/var/www/html'
    depends_on:
      - mysql

  mysql:
    container_name: 'mysql'
    image: 'mysql:5.7'
    ports:
        - '3306:3306'
    volumes:
        - './.docker/mysql/data:/var/lib/mysql'
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: auth_server
        MYSQL_USER: auth_server
        MYSQL_PASSWORD: auth_server

  adminer:
    image: 'adminer'
    restart: unless-stopped
    ports:
      - '8090:8080'